// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('app');

app.controller('IndexCtrl', function($scope) {
  $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
});
