// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('NavCtrl', function($scope, $location, Post) {
  $scope.post = {
    url: 'http://',
    title: ''
  };
  return $scope.submitPost = function() {
    return Post.create($scope.post).then(function(ref) {
      return $location.path('/post/' + ref.name());
    });
  };
});
