// Generated by CoffeeScript 1.7.1
'use strict';
app.controller('PostCtrl', function($scope, Post) {
  $scope.post = {
    url: 'http://',
    title: ''
  };
  $scope.posts = Post.get();
  $scope.submitPost = function() {
    return Post.save($scope.post, function(ref) {
      console.log(ref);
      $scope.posts[ref.name] = $scope.post;
      return $scope.post = {
        url: 'http://',
        title: ''
      };
    });
  };
  return $scope.deletePost = function(postId) {
    return Post["delete"]({
      id: postId
    }, function() {
      return delete $scope.posts[postId];
    });
  };
});
