// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('app.directives', []);

app.directive('enter', function() {
  return {
    restrict: 'E',
    template: '<a ng-transclude></a>',
    replace: true,
    transclude: true,
    compile: function(element) {
      element.addClass('index-enter');
      return element.addClass('index-enter-inverse');
    },
    link: function() {
      return console.log(123);
    }
  };
});
