// Generated by CoffeeScript 1.7.1
'use strict';
app.filter('hostnameFromUrl', function() {
  return function(str) {
    var url;
    url = document.createElement('a');
    url.href = str;
    return url.hostname;
  };
});
