// Generated by CoffeeScript 1.7.1
'use strict';
var app;

app = angular.module('app');

app.constant('FIREBASE_URL', 'https://luminous-fire-9425.firebaseio.com/');

app.factory('Post', function($firebase, FIREBASE_URL) {
  var posts, postsRef;
  postsRef = new Firebase(FIREBASE_URL + 'posts');
  posts = $firebase(postsRef);
  return {
    all: posts,
    create: function(post) {
      return posts.$add(post);
    },
    find: function(postId) {
      return posts.$child(postId);
    },
    "delete": function(postId) {
      return posts.$remove(postId);
    }
  };
});
